sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qc3Q8alJ2GIZGn6AthA2AuKt+HZeu2gET+dRV/ut1sIpqYJu4H3SWM8lGmlsbojJJqSrqCLVilmGjbrzoLaWFB9crV5wiLGwvizJ6tzv4JUJkDbZwAv3/GKmJvj+glKtR3TbfFn2NDaJDoqJTl/OZ1ZQ6HmpVtvpnbziNC63sAKxOp4s1NYrKXIpEoseqjX7IgUQ2Z+ToGcXLsr61LNc6QCj6zvxw8YcwsSP6rlus5YSasxJ/vNoybYYAX/kvpK7olS0tzu6+YozI8i4nQmP3jB7lkfX2dRXpowSDmNMvlujA8EYY944y6dvueL+oZnqfoQOVAYC+begQ6uZaWkicqqZyI8w6u+9H8IQkkBbBXzLegti0zSfONCweTxc5yRRuHzGCw6nE0I1zxZFntdhrnrcv16OgZ5jVWpt7amklklyV9e20kY8+EgaCxreIF/NroH/qHLoxnZrSuTMtdtmVSprHGUJa0oVhEG5kbrfTiLasWf3/2jshTE4NxYA3OQzghsEXt48E5zALsyQAFN5ZMSZoIsN1V+BvsHqAiTIPZn+24jR0qJSghsbM50aMIYNmdC3GuQ7xHmR5Ijb6pgzDKHxFA7notLvT5xN+k+ptSZrbeACS+AcY13hLBM7lJOkQs4FpxtBBKZEyTcO60nuy/qUYDoAVvbDyXCbvroLblU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Benita-an-African-romance_2761
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy